package settings

var SettingDefaults = map[string]string{
	"site_name":                    "皮肤站",
	"site_subtitle":                "简洁、高效、现代的 Minecraft 皮肤管理站",
	"require_invite":               "false",
	"allow_register":               "true",
	"enable_skin_library":          "true",
	"max_texture_size":             "1024",
	"footer_text":                  "",
	"filing_icp":                   "",
	"filing_icp_link":              "",
	"filing_mps":                   "",
	"filing_mps_link":              "",
	"profile_uuid_mode":            "random",
	"site_url":                     "",
	"api_url":                      "",
	"rate_limit_enabled":           "true",
	"rate_limit_auth_attempts":     "5",
	"rate_limit_auth_window":       "15",
	"enable_strong_password_check": "false",
	"jwt_expire_days":              "7",
	"microsoft_client_id":          "",
	"microsoft_client_secret":      "",
	"microsoft_redirect_uri":       "",
	"smtp_host":                    "",
	"smtp_port":                    "465",
	"smtp_user":                    "",
	"smtp_username":                "",
	"smtp_password":                "",
	"smtp_ssl":                     "true",
	"smtp_sender":                  "",
	"email_verify_enabled":         "false",
	"email_verify_ttl":             "300",
	"fallback_strategy":            "serial",
	"fallback_services":            "[]",
	"easter_eggs_enabled":          `["spring-festival","april-fools","dragon-boat"]`,
}

var settingsGroups = map[string][]string{
	"site": {
		"site_name", "allow_register", "require_invite", "enable_skin_library",
		"max_texture_size", "profile_uuid_mode", "site_url", "api_url",
		"site_subtitle", "footer_text", "filing_icp", "filing_icp_link", "filing_mps", "filing_mps_link",
	},
	"security":    {"rate_limit_enabled", "rate_limit_auth_attempts", "rate_limit_auth_window", "enable_strong_password_check"},
	"auth":        {"jwt_expire_days"},
	"microsoft":   {"microsoft_client_id", "microsoft_client_secret", "microsoft_redirect_uri"},
	"email":       {"smtp_host", "smtp_port", "smtp_user", "smtp_username", "smtp_password", "smtp_ssl", "smtp_sender", "email_verify_enabled", "email_verify_ttl"},
	"fallback":    {"fallback_strategy", "fallback_services"},
	"easter_eggs": {"easter_eggs_enabled"},
}
