package httpapi

import (
	"element-skin/backend/internal/httpapi/admin"
	identityapi "element-skin/backend/internal/httpapi/identity"
	"element-skin/backend/internal/httpapi/minecraft"
	"element-skin/backend/internal/httpapi/notice"
	"element-skin/backend/internal/httpapi/oauth"
	officialprofileapi "element-skin/backend/internal/httpapi/officialprofile"
	"element-skin/backend/internal/httpapi/remote"
	"element-skin/backend/internal/httpapi/site"
	"element-skin/backend/internal/httpapi/yggdrasil"
	"element-skin/backend/internal/permission"
)

func (r *Router) routes() {
	siteRoutes := site.NewWithRedis(r.cfg, r.db, r.redis, r.auth, r.mail)
	yggRoutes := yggdrasil.New(r.cfg, r.db, r.redis, r.settings, r.ygg)
	noticeRoutes := notice.New(r.db, r.auth)
	oauthRoutes := oauth.New(r.cfg, r.db, r.redis, r.auth, r.oidc)
	minecraftRoutes := minecraft.New(r.db, r.auth, r.ygg)
	remoteRoutes := remote.New(r.cfg, r.db, r.auth)
	adminRoutes := admin.NewWithRedis(r.cfg, r.db, r.redis, r.auth)
	identityRoutes := identityapi.New(r.cfg, r.db, r.redis, r.auth)
	officialProfileRoutes := officialprofileapi.New(r.cfg, r.db, r.redis, r.auth)
	sitePublicRead := permission.MustDefinitionByCode("site_public.read.public")
	texturePublicRead := permission.MustDefinitionByCode("texture.read.public")

	r.handle("GET /", r.publicAuth(yggRoutes.Metadata, sitePublicRead))
	r.handle("GET /api/publickeys", r.publicAuth(yggRoutes.PublicKeys, sitePublicRead))
	r.handle("GET /api/publickeys/", r.publicAuth(yggRoutes.PublicKeys, sitePublicRead))
	r.handle("GET /v2/capabilities", r.publicAuth(r.Capabilities, sitePublicRead))
	r.handle("GET /.well-known/oauth-authorization-server", oauthRoutes.AuthorizationServerMetadata)
	r.handle("GET /.well-known/openid-configuration", oauthRoutes.OpenIDConfiguration)
	r.handle("GET /.well-known/oauth-protected-resource", oauthRoutes.ProtectedResourceMetadata)
	r.handle("GET /v2/permissions/catalog", r.publicAuth(r.PermissionCatalog, sitePublicRead))
	r.handle("POST /v2/auth/login", siteRoutes.Login)
	r.handle("POST /v2/auth/logout", siteRoutes.Logout)
	r.handle("POST /v2/auth/register", siteRoutes.Register)
	r.handle("POST /v2/auth/verification-code", siteRoutes.SendVerificationCode)
	r.handle("POST /v2/auth/password/reset", siteRoutes.ResetPassword)
	r.handle("GET /v2/auth/identity-providers", r.publicAuth(identityRoutes.PublicProviders, permission.MustDefinitionByCode("identity_provider.read.public")))
	r.handle("POST /v2/identity-authorizations", r.publicAuth(identityRoutes.StartAuthorization, permission.MustDefinitionByCode("identity_provider.read.public")))
	r.handle("GET /v2/auth/oidc/callback", identityRoutes.AuthorizationCallback)
	r.handle("POST /v2/auth/session/refresh", siteRoutes.RefreshToken)
	r.handle("GET /v2/users/me", siteRoutes.Auth(siteRoutes.Me))
	r.handle("PATCH /v2/users/me", siteRoutes.Auth(siteRoutes.UpdateMe))
	r.handle("DELETE /v2/users/me", siteRoutes.Auth(siteRoutes.DeleteMe))
	r.handle("POST /v2/users/me/password", siteRoutes.Auth(siteRoutes.ChangePassword))
	r.handle("POST /v2/users/me/email/verification-code", siteRoutes.Auth(siteRoutes.SendEmailChangeCode))
	r.handle("PUT /v2/users/me/email", siteRoutes.Auth(siteRoutes.ChangeEmail))
	r.handle("GET /v2/users/me/identities", identityRoutes.Auth(identityRoutes.ListIdentities))
	r.handle("PATCH /v2/users/me/identities/{identity_id}", identityRoutes.Auth(identityRoutes.UpdateIdentity))
	r.handle("DELETE /v2/users/me/identities/{identity_id}", identityRoutes.Auth(identityRoutes.DeleteIdentity))
	r.handle("GET /v2/users/me/official-profile-bindings", officialProfileRoutes.Auth(officialProfileRoutes.List))
	r.handle("POST /v2/users/me/official-profile-bindings", officialProfileRoutes.Auth(officialProfileRoutes.Create))
	r.handle("POST /v2/users/me/official-profile-bindings/{binding_id}/sync", officialProfileRoutes.Auth(officialProfileRoutes.Sync))
	r.handle("DELETE /v2/users/me/official-profile-bindings/{binding_id}", officialProfileRoutes.Auth(officialProfileRoutes.Delete))
	r.handle("GET /v2/users/me/profiles", siteRoutes.Auth(siteRoutes.ListMyProfiles))
	r.handle("POST /v2/users/me/profiles", siteRoutes.Auth(siteRoutes.CreateProfile))
	r.handle("PATCH /v2/users/me/profiles/{profile_id}", siteRoutes.Auth(siteRoutes.UpdateProfile))
	r.handle("DELETE /v2/users/me/profiles/{profile_id}", siteRoutes.Auth(siteRoutes.DeleteProfile))
	r.handle("DELETE /v2/users/me/profiles/{profile_id}/skin", siteRoutes.Auth(siteRoutes.ClearProfileSkin))
	r.handle("DELETE /v2/users/me/profiles/{profile_id}/cape", siteRoutes.Auth(siteRoutes.ClearProfileCape))
	r.handle("GET /v2/users/me/textures", siteRoutes.Auth(siteRoutes.ListMyTextures))
	r.handle("POST /v2/users/me/textures", siteRoutes.Auth(siteRoutes.UploadMyTexture))
	r.handle("GET /v2/users/me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.TextureDetail))
	r.handle("PATCH /v2/users/me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.UpdateTexture))
	r.handle("DELETE /v2/users/me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.DeleteTexture))
	r.handle("POST /v2/users/me/textures/{hash}/wardrobe", siteRoutes.Auth(siteRoutes.AddTexture))
	r.handle("POST /v2/users/me/textures/{hash}/apply", siteRoutes.Auth(siteRoutes.ApplyTexture))
	r.handle("POST /v2/users/me/textures/upload-and-apply", siteRoutes.Auth(siteRoutes.UploadAndApplyTexture))
	r.handle("GET /v2/public/skin-library", r.publicAuth(siteRoutes.PublicLibrary, texturePublicRead))
	r.handle("GET /v2/public/settings", r.publicAuth(siteRoutes.PublicSettings, sitePublicRead))
	r.handle("GET /v2/public/homepage-media", r.publicAuth(siteRoutes.PublicHomepageMedia, sitePublicRead))
	r.handle("GET /v2/public/fallback-status", r.publicAuth(siteRoutes.PublicFallbackStatus, sitePublicRead))
	r.handle("GET /v2/minecraft/profiles/{path...}", r.publicAuth(minecraftRoutes.Profiles))
	r.handle("POST /v2/minecraft/profiles/by-names", r.publicAuth(minecraftRoutes.ProfilesByNames))
	r.handle("POST /v2/minecraft/session/has-joined", minecraftRoutes.Auth(
		minecraftRoutes.HasJoined,
		permission.MustDefinitionByCode("minecraft_session.hasjoined.server"),
	))
	r.handle("GET /v2/notifications", noticeRoutes.Auth(noticeRoutes.List))
	r.handle("GET /v2/notifications/{id}", noticeRoutes.Auth(noticeRoutes.Detail))
	r.handle("POST /v2/notifications/{id}/read", noticeRoutes.Auth(noticeRoutes.MarkRead))
	r.handle("POST /v2/notifications/{id}/dismiss", noticeRoutes.Auth(noticeRoutes.Dismiss))
	r.handle("GET /v2/oauth/apps", oauthRoutes.Auth(oauthRoutes.ListApps))
	r.handle("POST /v2/oauth/apps", oauthRoutes.Auth(oauthRoutes.CreateApp))
	r.handle("GET /v2/oauth/apps/{client_id}", oauthRoutes.Auth(oauthRoutes.GetApp))
	r.handle("PATCH /v2/oauth/apps/{client_id}", oauthRoutes.Auth(oauthRoutes.UpdateApp))
	r.handle("DELETE /v2/oauth/apps/{client_id}", oauthRoutes.Auth(oauthRoutes.DeleteApp))
	r.handle("POST /v2/oauth/apps/{client_id}/review-submission", oauthRoutes.Auth(oauthRoutes.SubmitAppReview))
	r.handle("POST /v2/oauth/apps/{client_id}/secret", oauthRoutes.Auth(oauthRoutes.RotateSecret))
	r.handle("GET /v2/oauth/apps/{client_id}/permissions", oauthRoutes.Auth(oauthRoutes.ClientPermissions))
	r.handle("PUT /v2/oauth/apps/{client_id}/permissions/{permission_code}", oauthRoutes.Auth(oauthRoutes.SetClientPermission))
	r.handle("DELETE /v2/oauth/apps/{client_id}/permissions/{permission_code}", oauthRoutes.Auth(oauthRoutes.ClearClientPermission))
	r.handle("GET /v2/oauth/grants", oauthRoutes.Auth(oauthRoutes.ListGrants))
	r.handle("DELETE /v2/oauth/grants/{grant_id}", oauthRoutes.Auth(oauthRoutes.RevokeGrant))
	r.handle("GET /oauth/authorize", oauthRoutes.Auth(oauthRoutes.AuthorizeInfo))
	r.handle("POST /oauth/authorize", oauthRoutes.Auth(oauthRoutes.ApproveAuthorization))
	r.handle("POST /oauth/device/code", oauthRoutes.DeviceCode)
	r.handle("GET /oauth/device", oauthRoutes.Auth(oauthRoutes.DeviceInfo))
	r.handle("POST /oauth/device", oauthRoutes.Auth(oauthRoutes.DeviceDecision))
	r.handle("POST /oauth/token", oauthRoutes.Token)
	r.handle("GET /oauth/jwks", oauthRoutes.JWKS)
	r.handle("GET /oauth/userinfo", oauthRoutes.UserInfo)
	r.handle("POST /oauth/revoke", oauthRoutes.Revoke)
	r.handle("POST /oauth/introspect", oauthRoutes.Auth(oauthRoutes.Introspect))

	r.handle("POST /authserver/authenticate", yggRoutes.Authenticate)
	r.handle("POST /authserver/refresh", yggRoutes.Refresh)
	r.handle("POST /authserver/validate", yggRoutes.Validate)
	r.handle("POST /authserver/invalidate", yggRoutes.Invalidate)
	r.handle("POST /authserver/signout", yggRoutes.Signout)
	r.handle("POST /sessionserver/session/minecraft/join", yggRoutes.Join)
	r.handle("GET /sessionserver/session/minecraft/hasJoined", yggRoutes.HasJoined)
	r.handle("GET /sessionserver/session/minecraft/profile/{uuid}", yggRoutes.Profile)
	r.handle("GET /api/users/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("GET /users/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("GET /api/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("POST /api/profiles/minecraft", yggRoutes.LookupNames)
	r.handle("GET /api/minecraft/profile/lookup/name/{playerName}", yggRoutes.LookupName)
	r.handle("GET /minecraft/profile/lookup/name/{playerName}", yggRoutes.LookupName)
	r.handle("PUT /api/user/profile/{uuid}/{texture_type}", yggRoutes.UploadTexture)
	r.handle("DELETE /api/user/profile/{uuid}/{texture_type}", yggRoutes.DeleteTexture)
	r.handle("POST /v2/imports/remote-ygg/profiles/preview", remoteRoutes.Auth(remoteRoutes.GetProfiles))
	r.handle("POST /v2/imports/remote-ygg/profiles/import", remoteRoutes.Auth(remoteRoutes.ImportProfile))
	r.handle("POST /v2/imports/remote-ygg/profiles/import-batch", remoteRoutes.Auth(remoteRoutes.ImportProfiles))

	r.handle("GET /v2/admin/users", adminRoutes.Auth(adminRoutes.Users))
	r.handle("GET /v2/admin/users/{user_id}", adminRoutes.Auth(adminRoutes.User))
	r.handle("GET /v2/admin/users/{user_id}/profiles", adminRoutes.Auth(adminRoutes.UserProfiles))
	r.handle("GET /v2/admin/users/{user_id}/permissions", adminRoutes.Auth(adminRoutes.UserPermissions))
	r.handle("PUT /v2/admin/users/{user_id}/roles/{role_id}", adminRoutes.Auth(adminRoutes.GrantUserRole))
	r.handle("DELETE /v2/admin/users/{user_id}/roles/{role_id}", adminRoutes.Auth(adminRoutes.RevokeUserRole))
	r.handle("POST /v2/admin/users/{user_id}/protected-subject/transfer", adminRoutes.Auth(adminRoutes.TransferProtectedSubject))
	r.handle("PUT /v2/admin/users/{user_id}/permissions/{permission_code}", adminRoutes.Auth(adminRoutes.SetUserPermissionOverride))
	r.handle("DELETE /v2/admin/users/{user_id}/permissions/{permission_code}", adminRoutes.Auth(adminRoutes.ClearUserPermissionOverride))
	r.handle("DELETE /v2/admin/users/{user_id}", adminRoutes.Auth(adminRoutes.DeleteUser))
	r.handle("POST /v2/admin/users/{user_id}/ban", adminRoutes.Auth(adminRoutes.BanUser))
	r.handle("POST /v2/admin/users/{user_id}/unban", adminRoutes.Auth(adminRoutes.UnbanUser))
	r.handle("POST /v2/admin/users/password/reset", adminRoutes.Auth(adminRoutes.ResetUserPassword))
	r.handle("GET /v2/admin/oauth/apps", oauthRoutes.Auth(oauthRoutes.ListAdminApps))
	r.handle("GET /v2/admin/oauth/apps/{client_id}", oauthRoutes.Auth(oauthRoutes.GetApp))
	r.handle("PATCH /v2/admin/oauth/apps/{client_id}/review", oauthRoutes.Auth(oauthRoutes.ReviewApp))
	r.handle("GET /v2/admin/profiles", adminRoutes.Auth(adminRoutes.Profiles))
	r.handle("PATCH /v2/admin/profiles/{profile_id}", adminRoutes.Auth(adminRoutes.UpdateProfile))
	r.handle("DELETE /v2/admin/profiles/{profile_id}", adminRoutes.Auth(adminRoutes.DeleteProfile))
	r.handle("PATCH /v2/admin/profiles/{profile_id}/skin", adminRoutes.Auth(adminRoutes.UpdateProfileSkin))
	r.handle("PATCH /v2/admin/profiles/{profile_id}/cape", adminRoutes.Auth(adminRoutes.UpdateProfileCape))
	r.handle("GET /v2/admin/textures", adminRoutes.Auth(adminRoutes.Textures))
	r.handle("PATCH /v2/admin/textures/{hash}", adminRoutes.Auth(adminRoutes.UpdateTexture))
	r.handle("DELETE /v2/admin/textures/{hash}", adminRoutes.Auth(adminRoutes.DeleteTexture))
	r.handle("GET /v2/admin/invites", adminRoutes.Auth(adminRoutes.Invites))
	r.handle("POST /v2/admin/invites", adminRoutes.Auth(adminRoutes.CreateInvite))
	r.handle("DELETE /v2/admin/invites/{code}", adminRoutes.Auth(adminRoutes.DeleteInvite))
	r.handle("GET /v2/admin/official-whitelist", adminRoutes.Auth(adminRoutes.OfficialWhitelist))
	r.handle("POST /v2/admin/official-whitelist", adminRoutes.Auth(adminRoutes.AddOfficialWhitelist))
	r.handle("DELETE /v2/admin/official-whitelist/{username}", adminRoutes.Auth(adminRoutes.RemoveOfficialWhitelist))
	r.handle("GET /v2/admin/homepage-media", adminRoutes.Auth(adminRoutes.ListHomepageMedia))
	r.handle("POST /v2/admin/homepage-media/image", adminRoutes.Auth(adminRoutes.UploadHomepageImage))
	r.handle("POST /v2/admin/homepage-media/panorama", adminRoutes.Auth(adminRoutes.UploadHomepagePanorama))
	r.handle("PATCH /v2/admin/homepage-media/reorder", adminRoutes.Auth(adminRoutes.ReorderHomepageMedia))
	r.handle("PATCH /v2/admin/homepage-media/{id}", adminRoutes.Auth(adminRoutes.PatchHomepageMedia))
	r.handle("DELETE /v2/admin/homepage-media/{id}", adminRoutes.Auth(adminRoutes.DeleteHomepageMedia))
	r.handle("GET /v2/admin/notifications", adminRoutes.Auth(adminRoutes.Notices))
	r.handle("POST /v2/admin/notifications", adminRoutes.Auth(adminRoutes.CreateNotice))
	r.handle("PATCH /v2/admin/notifications/{id}", adminRoutes.Auth(adminRoutes.PatchNotice))
	r.handle("DELETE /v2/admin/notifications/{id}", adminRoutes.Auth(adminRoutes.DeleteNotice))
	r.handle("GET /v2/admin/settings/site", adminRoutes.Auth(adminRoutes.GetSiteSettings))
	r.handle("POST /v2/admin/settings/site", adminRoutes.Auth(adminRoutes.SaveSiteSettings))
	r.handle("GET /v2/admin/settings/email-suffix-policy", adminRoutes.Auth(adminRoutes.GetEmailSuffixPolicy))
	r.handle("PUT /v2/admin/settings/email-suffix-policy", adminRoutes.Auth(adminRoutes.PutEmailSuffixPolicy))
	r.handle("GET /v2/admin/settings/{group}", adminRoutes.Auth(adminRoutes.GetSettingsGroup))
	r.handle("POST /v2/admin/settings/{group}", adminRoutes.Auth(adminRoutes.SaveSettingsGroup))
	r.handle("GET /v2/admin/identity-providers", identityRoutes.Auth(identityRoutes.ListProviders))
	r.handle("POST /v2/admin/identity-providers", identityRoutes.Auth(identityRoutes.CreateProvider))
	r.handle("GET /v2/admin/identity-providers/{provider_id}", identityRoutes.Auth(identityRoutes.GetProvider))
	r.handle("PUT /v2/admin/identity-providers/{provider_id}", identityRoutes.Auth(identityRoutes.UpdateProvider))
	r.handle("DELETE /v2/admin/identity-providers/{provider_id}", identityRoutes.Auth(identityRoutes.DeleteProvider))
}
