package httpapi

import (
	"element-skin/backend/internal/httpapi/admin"
	"element-skin/backend/internal/httpapi/microsoft"
	"element-skin/backend/internal/httpapi/minecraft"
	"element-skin/backend/internal/httpapi/notice"
	"element-skin/backend/internal/httpapi/oauth"
	"element-skin/backend/internal/httpapi/remote"
	"element-skin/backend/internal/httpapi/site"
	"element-skin/backend/internal/httpapi/yggdrasil"
	"element-skin/backend/internal/permission"
)

func (r *Router) routes() {
	siteRoutes := site.NewWithRedis(r.cfg, r.db, r.redis, r.site, r.auth)
	yggRoutes := yggdrasil.New(r.cfg, r.db, r.redis, r.settings, r.ygg)
	microsoftRoutes := microsoft.New(r.cfg, r.db, r.settings, r.auth, r.redis)
	noticeRoutes := notice.New(r.db, r.auth)
	oauthRoutes := oauth.New(r.cfg, r.db, r.auth)
	minecraftRoutes := minecraft.New(r.db, r.auth, r.ygg)
	remoteRoutes := remote.New(r.db, r.auth)
	adminRoutes := admin.NewWithRedis(r.cfg, r.db, r.redis, r.auth)

	r.handle("GET /", yggRoutes.Metadata)
	r.handle("GET /v1/capabilities", r.Capabilities)
	r.handle("GET /.well-known/oauth-authorization-server", oauthRoutes.AuthorizationServerMetadata)
	r.handle("GET /.well-known/oauth-protected-resource", oauthRoutes.ProtectedResourceMetadata)
	r.handle("GET /v1/permissions/catalog", r.PermissionCatalog)
	r.handle("POST /v1/auth/login", siteRoutes.Login)
	r.handle("POST /v1/auth/logout", siteRoutes.Logout)
	r.handle("POST /v1/auth/register", siteRoutes.Register)
	r.handle("POST /v1/auth/verification-code", siteRoutes.SendVerificationCode)
	r.handle("POST /v1/auth/password/reset", siteRoutes.ResetPassword)
	r.handle("POST /v1/auth/session/refresh", siteRoutes.RefreshToken)
	r.handle("GET /v1/users/me", siteRoutes.Auth(siteRoutes.Me))
	r.handle("PATCH /v1/users/me", siteRoutes.Auth(siteRoutes.UpdateMe))
	r.handle("DELETE /v1/users/me", siteRoutes.Auth(siteRoutes.DeleteMe))
	r.handle("POST /v1/users/me/password", siteRoutes.Auth(siteRoutes.ChangePassword))
	r.handle("GET /v1/users/me/profiles", siteRoutes.Auth(siteRoutes.ListMyProfiles))
	r.handle("POST /v1/users/me/profiles", siteRoutes.Auth(siteRoutes.CreateProfile))
	r.handle("PATCH /v1/users/me/profiles/{profile_id}", siteRoutes.Auth(siteRoutes.UpdateProfile))
	r.handle("DELETE /v1/users/me/profiles/{profile_id}", siteRoutes.Auth(siteRoutes.DeleteProfile))
	r.handle("DELETE /v1/users/me/profiles/{profile_id}/skin", siteRoutes.Auth(siteRoutes.ClearProfileSkin))
	r.handle("DELETE /v1/users/me/profiles/{profile_id}/cape", siteRoutes.Auth(siteRoutes.ClearProfileCape))
	r.handle("GET /v1/users/me/textures", siteRoutes.Auth(siteRoutes.ListMyTextures))
	r.handle("POST /v1/users/me/textures", siteRoutes.Auth(siteRoutes.UploadMyTexture))
	r.handle("GET /v1/users/me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.TextureDetail))
	r.handle("PATCH /v1/users/me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.UpdateTexture))
	r.handle("DELETE /v1/users/me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.DeleteTexture))
	r.handle("POST /v1/users/me/textures/{hash}/wardrobe", siteRoutes.Auth(siteRoutes.AddTexture))
	r.handle("POST /v1/users/me/textures/{hash}/apply", siteRoutes.Auth(siteRoutes.ApplyTexture))
	r.handle("POST /v1/users/me/textures/upload-and-apply", siteRoutes.Auth(siteRoutes.UploadAndApplyTexture))
	r.handle("GET /v1/public/skin-library", siteRoutes.PublicLibrary)
	r.handle("GET /v1/public/settings", siteRoutes.PublicSettings)
	r.handle("GET /v1/public/homepage-media", siteRoutes.PublicHomepageMedia)
	r.handle("GET /v1/public/fallback-status", siteRoutes.PublicFallbackStatus)
	r.handle("GET /v1/minecraft/profiles/{path...}", minecraftRoutes.Profiles)
	r.handle("POST /v1/minecraft/profiles/by-names", minecraftRoutes.ProfilesByNames)
	r.handle("POST /v1/minecraft/session/has-joined", minecraftRoutes.Auth(
		minecraftRoutes.HasJoined,
		permission.MustDefinitionByCode("minecraft_session.hasjoined.server"),
	))
	r.handle("GET /v1/notifications", noticeRoutes.Auth(noticeRoutes.List))
	r.handle("GET /v1/notifications/{id}", noticeRoutes.Auth(noticeRoutes.Detail))
	r.handle("POST /v1/notifications/{id}/read", noticeRoutes.Auth(noticeRoutes.MarkRead))
	r.handle("POST /v1/notifications/{id}/dismiss", noticeRoutes.Auth(noticeRoutes.Dismiss))
	r.handle("GET /v1/oauth/apps", oauthRoutes.Auth(oauthRoutes.ListApps))
	r.handle("POST /v1/oauth/apps", oauthRoutes.Auth(oauthRoutes.CreateApp))
	r.handle("GET /v1/oauth/apps/{client_id}", oauthRoutes.Auth(oauthRoutes.GetApp))
	r.handle("PATCH /v1/oauth/apps/{client_id}", oauthRoutes.Auth(oauthRoutes.UpdateApp))
	r.handle("DELETE /v1/oauth/apps/{client_id}", oauthRoutes.Auth(oauthRoutes.DeleteApp))
	r.handle("POST /v1/oauth/apps/{client_id}/secret", oauthRoutes.Auth(oauthRoutes.RotateSecret))
	r.handle("GET /v1/oauth/apps/{client_id}/permissions", oauthRoutes.Auth(oauthRoutes.ClientPermissions))
	r.handle("PUT /v1/oauth/apps/{client_id}/permissions/{permission_code}", oauthRoutes.Auth(oauthRoutes.SetClientPermission))
	r.handle("DELETE /v1/oauth/apps/{client_id}/permissions/{permission_code}", oauthRoutes.Auth(oauthRoutes.ClearClientPermission))
	r.handle("GET /v1/oauth/grants", oauthRoutes.Auth(oauthRoutes.ListGrants))
	r.handle("DELETE /v1/oauth/grants/{grant_id}", oauthRoutes.Auth(oauthRoutes.RevokeGrant))
	r.handle("GET /oauth/authorize", oauthRoutes.Auth(oauthRoutes.AuthorizeInfo))
	r.handle("POST /oauth/authorize", oauthRoutes.Auth(oauthRoutes.ApproveAuthorization))
	r.handle("POST /oauth/device/code", oauthRoutes.DeviceCode)
	r.handle("GET /oauth/device", oauthRoutes.Auth(oauthRoutes.DeviceInfo))
	r.handle("POST /oauth/device", oauthRoutes.Auth(oauthRoutes.DeviceDecision))
	r.handle("POST /oauth/token", oauthRoutes.Token)
	r.handle("POST /oauth/revoke", oauthRoutes.Revoke)
	r.handle("POST /oauth/introspect", oauthRoutes.Auth(oauthRoutes.Introspect))

	r.handle("POST /authserver/authenticate", yggRoutes.Authenticate)
	r.handle("POST /authserver/refresh", yggRoutes.Refresh)
	r.handle("POST /authserver/validate", yggRoutes.Validate)
	r.handle("POST /authserver/invalidate", yggRoutes.Invalidate)
	r.handle("POST /authserver/signout", yggRoutes.Signout)
	r.handle("POST /sessionserver/session/minecraft/join", yggRoutes.Join)
	r.handle("GET /sessionserver/session/minecraft/hasJoined", yggRoutes.HasJoined)
	r.handle("GET /sessionserver/session/minecraft/profile/{uuid}", yggRoutes.Profile)
	r.handle("GET /api/users/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("GET /users/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("GET /api/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("POST /api/profiles/minecraft", yggRoutes.LookupNames)
	r.handle("GET /api/minecraft/profile/lookup/name/{playerName}", yggRoutes.LookupName)
	r.handle("GET /minecraft/profile/lookup/name/{playerName}", yggRoutes.LookupName)
	r.handle("PUT /api/user/profile/{uuid}/{texture_type}", yggRoutes.UploadTexture)
	r.handle("DELETE /api/user/profile/{uuid}/{texture_type}", yggRoutes.DeleteTexture)
	r.handle("GET /v1/imports/microsoft/auth-url", microsoftRoutes.Auth(microsoftRoutes.AuthURL))
	r.handle("GET /v1/imports/microsoft/callback", microsoftRoutes.Callback)
	r.handle("POST /v1/imports/microsoft/profile", microsoftRoutes.Auth(microsoftRoutes.GetProfile))
	r.handle("POST /v1/imports/microsoft/profile/import", microsoftRoutes.Auth(microsoftRoutes.ImportProfile))
	r.handle("POST /v1/imports/remote-ygg/profiles/preview", remoteRoutes.Auth(remoteRoutes.GetProfiles))
	r.handle("POST /v1/imports/remote-ygg/profiles/import", remoteRoutes.Auth(remoteRoutes.ImportProfile))
	r.handle("POST /v1/imports/remote-ygg/profiles/import-batch", remoteRoutes.Auth(remoteRoutes.ImportProfiles))

	r.handle("GET /v1/admin/users", adminRoutes.Auth(adminRoutes.Users))
	r.handle("GET /v1/admin/users/{user_id}", adminRoutes.Auth(adminRoutes.User))
	r.handle("GET /v1/admin/users/{user_id}/profiles", adminRoutes.Auth(adminRoutes.UserProfiles))
	r.handle("GET /v1/admin/users/{user_id}/permissions", adminRoutes.Auth(adminRoutes.UserPermissions))
	r.handle("PUT /v1/admin/users/{user_id}/roles/{role_id}", adminRoutes.Auth(adminRoutes.GrantUserRole))
	r.handle("DELETE /v1/admin/users/{user_id}/roles/{role_id}", adminRoutes.Auth(adminRoutes.RevokeUserRole))
	r.handle("PUT /v1/admin/users/{user_id}/permissions/{permission_code}", adminRoutes.Auth(adminRoutes.SetUserPermissionOverride))
	r.handle("DELETE /v1/admin/users/{user_id}/permissions/{permission_code}", adminRoutes.Auth(adminRoutes.ClearUserPermissionOverride))
	r.handle("DELETE /v1/admin/users/{user_id}", adminRoutes.Auth(adminRoutes.DeleteUser))
	r.handle("POST /v1/admin/users/{user_id}/ban", adminRoutes.Auth(adminRoutes.BanUser))
	r.handle("POST /v1/admin/users/{user_id}/unban", adminRoutes.Auth(adminRoutes.UnbanUser))
	r.handle("POST /v1/admin/users/password/reset", adminRoutes.Auth(adminRoutes.ResetUserPassword))
	r.handle("GET /v1/admin/profiles", adminRoutes.Auth(adminRoutes.Profiles))
	r.handle("PATCH /v1/admin/profiles/{profile_id}", adminRoutes.Auth(adminRoutes.UpdateProfile))
	r.handle("DELETE /v1/admin/profiles/{profile_id}", adminRoutes.Auth(adminRoutes.DeleteProfile))
	r.handle("PATCH /v1/admin/profiles/{profile_id}/skin", adminRoutes.Auth(adminRoutes.UpdateProfileSkin))
	r.handle("PATCH /v1/admin/profiles/{profile_id}/cape", adminRoutes.Auth(adminRoutes.UpdateProfileCape))
	r.handle("GET /v1/admin/textures", adminRoutes.Auth(adminRoutes.Textures))
	r.handle("PATCH /v1/admin/textures/{hash}", adminRoutes.Auth(adminRoutes.UpdateTexture))
	r.handle("DELETE /v1/admin/textures/{hash}", adminRoutes.Auth(adminRoutes.DeleteTexture))
	r.handle("GET /v1/admin/invites", adminRoutes.Auth(adminRoutes.Invites))
	r.handle("POST /v1/admin/invites", adminRoutes.Auth(adminRoutes.CreateInvite))
	r.handle("DELETE /v1/admin/invites/{code}", adminRoutes.Auth(adminRoutes.DeleteInvite))
	r.handle("GET /v1/admin/official-whitelist", adminRoutes.Auth(adminRoutes.OfficialWhitelist))
	r.handle("POST /v1/admin/official-whitelist", adminRoutes.Auth(adminRoutes.AddOfficialWhitelist))
	r.handle("DELETE /v1/admin/official-whitelist/{username}", adminRoutes.Auth(adminRoutes.RemoveOfficialWhitelist))
	r.handle("GET /v1/admin/homepage-media", adminRoutes.Auth(adminRoutes.ListHomepageMedia))
	r.handle("POST /v1/admin/homepage-media/image", adminRoutes.Auth(adminRoutes.UploadHomepageImage))
	r.handle("POST /v1/admin/homepage-media/panorama", adminRoutes.Auth(adminRoutes.UploadHomepagePanorama))
	r.handle("PATCH /v1/admin/homepage-media/reorder", adminRoutes.Auth(adminRoutes.ReorderHomepageMedia))
	r.handle("PATCH /v1/admin/homepage-media/{id}", adminRoutes.Auth(adminRoutes.PatchHomepageMedia))
	r.handle("DELETE /v1/admin/homepage-media/{id}", adminRoutes.Auth(adminRoutes.DeleteHomepageMedia))
	r.handle("GET /v1/admin/notifications", adminRoutes.Auth(adminRoutes.Notices))
	r.handle("POST /v1/admin/notifications", adminRoutes.Auth(adminRoutes.CreateNotice))
	r.handle("PATCH /v1/admin/notifications/{id}", adminRoutes.Auth(adminRoutes.PatchNotice))
	r.handle("DELETE /v1/admin/notifications/{id}", adminRoutes.Auth(adminRoutes.DeleteNotice))
	r.handle("GET /v1/admin/settings/site", adminRoutes.Auth(adminRoutes.GetSiteSettings))
	r.handle("POST /v1/admin/settings/site", adminRoutes.Auth(adminRoutes.SaveSiteSettings))
	r.handle("GET /v1/admin/settings/{group}", adminRoutes.Auth(adminRoutes.GetSettingsGroup))
	r.handle("POST /v1/admin/settings/{group}", adminRoutes.Auth(adminRoutes.SaveSettingsGroup))
}
