package httpapi

import (
	"element-skin/backend/internal/httpapi/admin"
	"element-skin/backend/internal/httpapi/microsoft"
	"element-skin/backend/internal/httpapi/remote"
	"element-skin/backend/internal/httpapi/site"
	"element-skin/backend/internal/httpapi/yggdrasil"
)

func (r *Router) routes() {
	siteRoutes := site.NewWithRedis(r.cfg, r.db, r.redis, r.site, r.auth)
	yggRoutes := yggdrasil.New(r.cfg, r.db, r.settings, r.ygg)
	microsoftRoutes := microsoft.New(r.cfg, r.db, r.settings, r.auth, MicrosoftImportStates)
	remoteRoutes := remote.New(r.db, r.auth)
	adminRoutes := admin.NewWithRedis(r.cfg, r.db, r.redis, r.auth)

	r.handle("GET /", yggRoutes.Metadata)
	r.handle("POST /site-login", siteRoutes.Login)
	r.handle("POST /site-logout", siteRoutes.Logout)
	r.handle("POST /register", siteRoutes.Register)
	r.handle("POST /send-verification-code", siteRoutes.SendVerificationCode)
	r.handle("POST /reset-password", siteRoutes.ResetPassword)
	r.handle("GET /me", siteRoutes.Auth(siteRoutes.Me))
	r.handle("PATCH /me", siteRoutes.Auth(siteRoutes.UpdateMe))
	r.handle("DELETE /me", siteRoutes.Auth(siteRoutes.DeleteMe))
	r.handle("POST /me/password", siteRoutes.Auth(siteRoutes.ChangePassword))
	r.handle("POST /me/refresh-token", siteRoutes.RefreshToken)
	r.handle("GET /me/profiles", siteRoutes.Auth(siteRoutes.ListMyProfiles))
	r.handle("POST /me/profiles", siteRoutes.Auth(siteRoutes.CreateProfile))
	r.handle("PATCH /me/profiles/{pid}", siteRoutes.Auth(siteRoutes.UpdateProfile))
	r.handle("DELETE /me/profiles/{pid}", siteRoutes.Auth(siteRoutes.DeleteProfile))
	r.handle("DELETE /me/profiles/{pid}/skin", siteRoutes.Auth(siteRoutes.ClearProfileSkin))
	r.handle("DELETE /me/profiles/{pid}/cape", siteRoutes.Auth(siteRoutes.ClearProfileCape))
	r.handle("GET /me/textures", siteRoutes.Auth(siteRoutes.ListMyTextures))
	r.handle("POST /me/textures", siteRoutes.Auth(siteRoutes.UploadMyTexture))
	r.handle("GET /me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.TextureDetail))
	r.handle("PATCH /me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.UpdateTexture))
	r.handle("DELETE /me/textures/{hash}/{texture_type}", siteRoutes.Auth(siteRoutes.DeleteTexture))
	r.handle("POST /me/textures/{hash}/add", siteRoutes.Auth(siteRoutes.AddTexture))
	r.handle("POST /me/textures/{hash}/apply", siteRoutes.Auth(siteRoutes.ApplyTexture))
	r.handle("POST /textures/upload", siteRoutes.Auth(siteRoutes.UploadAndApplyTexture))
	r.handle("GET /public/skin-library", siteRoutes.PublicLibrary)
	r.handle("GET /public/settings", siteRoutes.PublicSettings)
	r.handle("GET /public/carousel", siteRoutes.PublicCarousel)

	r.handle("POST /authserver/authenticate", yggRoutes.Authenticate)
	r.handle("POST /authserver/refresh", yggRoutes.Refresh)
	r.handle("POST /authserver/validate", yggRoutes.Validate)
	r.handle("POST /authserver/invalidate", yggRoutes.Invalidate)
	r.handle("POST /authserver/signout", yggRoutes.Signout)
	r.handle("POST /sessionserver/session/minecraft/join", yggRoutes.Join)
	r.handle("GET /sessionserver/session/minecraft/hasJoined", yggRoutes.HasJoined)
	r.handle("GET /sessionserver/session/minecraft/profile/{uuid}", yggRoutes.Profile)
	r.handle("GET /api/users/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("GET /users/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("GET /api/profiles/minecraft/{playerName}", yggRoutes.LookupName)
	r.handle("POST /api/profiles/minecraft", yggRoutes.LookupNames)
	r.handle("GET /api/minecraft/profile/lookup/name/{playerName}", yggRoutes.LookupName)
	r.handle("GET /minecraft/profile/lookup/name/{playerName}", yggRoutes.LookupName)
	r.handle("PUT /api/user/profile/{uuid}/{texture_type}", yggRoutes.UploadTexture)
	r.handle("DELETE /api/user/profile/{uuid}/{texture_type}", yggRoutes.DeleteTexture)
	r.handle("GET /microsoft/auth-url", microsoftRoutes.Auth(microsoftRoutes.AuthURL))
	r.handle("GET /microsoft/callback", microsoftRoutes.Callback)
	r.handle("POST /microsoft/get-profile", microsoftRoutes.Auth(microsoftRoutes.GetProfile))
	r.handle("POST /microsoft/import-profile", microsoftRoutes.Auth(microsoftRoutes.ImportProfile))
	r.handle("POST /remote-ygg/get-profiles", remoteRoutes.Auth(remoteRoutes.GetProfiles))
	r.handle("POST /remote-ygg/import-profile", remoteRoutes.Auth(remoteRoutes.ImportProfile))
	r.handle("POST /remote-ygg/import-profiles", remoteRoutes.Auth(remoteRoutes.ImportProfiles))

	r.handle("GET /admin/users", adminRoutes.Auth(adminRoutes.Users))
	r.handle("GET /admin/users/{user_id}", adminRoutes.Auth(adminRoutes.User))
	r.handle("GET /admin/users/{user_id}/profiles", adminRoutes.Auth(adminRoutes.UserProfiles))
	r.handle("POST /admin/users/{user_id}/toggle-admin", adminRoutes.Auth(adminRoutes.ToggleUserAdmin))
	r.handle("DELETE /admin/users/{user_id}", adminRoutes.Auth(adminRoutes.DeleteUser))
	r.handle("POST /admin/users/{user_id}/ban", adminRoutes.Auth(adminRoutes.BanUser))
	r.handle("POST /admin/users/{user_id}/unban", adminRoutes.Auth(adminRoutes.UnbanUser))
	r.handle("POST /admin/users/reset-password", adminRoutes.Auth(adminRoutes.ResetUserPassword))
	r.handle("GET /admin/profiles", adminRoutes.Auth(adminRoutes.Profiles))
	r.handle("PATCH /admin/profiles/{profile_id}", adminRoutes.Auth(adminRoutes.UpdateProfile))
	r.handle("DELETE /admin/profiles/{profile_id}", adminRoutes.Auth(adminRoutes.DeleteProfile))
	r.handle("PATCH /admin/profiles/{profile_id}/skin", adminRoutes.Auth(adminRoutes.UpdateProfileSkin))
	r.handle("PATCH /admin/profiles/{profile_id}/cape", adminRoutes.Auth(adminRoutes.UpdateProfileCape))
	r.handle("GET /admin/textures", adminRoutes.Auth(adminRoutes.Textures))
	r.handle("PATCH /admin/textures/{hash}", adminRoutes.Auth(adminRoutes.UpdateTexture))
	r.handle("DELETE /admin/textures/{hash}", adminRoutes.Auth(adminRoutes.DeleteTexture))
	r.handle("GET /admin/invites", adminRoutes.Auth(adminRoutes.Invites))
	r.handle("POST /admin/invites", adminRoutes.Auth(adminRoutes.CreateInvite))
	r.handle("DELETE /admin/invites/{code}", adminRoutes.Auth(adminRoutes.DeleteInvite))
	r.handle("GET /admin/official-whitelist", adminRoutes.Auth(adminRoutes.OfficialWhitelist))
	r.handle("POST /admin/official-whitelist", adminRoutes.Auth(adminRoutes.AddOfficialWhitelist))
	r.handle("DELETE /admin/official-whitelist/{username}", adminRoutes.Auth(adminRoutes.RemoveOfficialWhitelist))
	r.handle("POST /admin/carousel", adminRoutes.Auth(adminRoutes.UploadCarousel))
	r.handle("DELETE /admin/carousel/{filename}", adminRoutes.Auth(adminRoutes.DeleteCarousel))
	r.handle("GET /admin/settings/site", adminRoutes.Auth(adminRoutes.GetSiteSettings))
	r.handle("POST /admin/settings/site", adminRoutes.Auth(adminRoutes.SaveSiteSettings))
	r.handle("GET /admin/settings/{group}", adminRoutes.Auth(adminRoutes.GetSettingsGroup))
	r.handle("POST /admin/settings/{group}", adminRoutes.Auth(adminRoutes.SaveSettingsGroup))
}
